---
swagger: "2.0"
info:
  description: "API server for the variant app"
  version: "1.0.0"
  title: "Variant API"
  contact:
    email: "brendanfliu@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "virtserver.swaggerhub.com"
basePath: "/invitae/bliu"
tags:
  - name: "developers"
    description: "Operations available to regular developers"
schemes:
  - "https"
paths:
  /variant:
    get:
      summary: "List all variants"
      description: ""
      operationId: "get_variant"
      produces:
        - "application/json"
      parameters:
              - name: gene
                in: query
                required: false
                type: "string"
      responses:
        200:
          description: "search results matching criteria"
          schema:
            type: "array"
            items:
              type: "object"
      x-swagger-router-controller: "swagger_server.controllers.developers_controller"
  /gene:
    get:
      summary: "List all genes"
      description: ""
      operationId: "get_gene"
      produces:
        - "application/json"
      parameters:
        - name: "gene_prefix"
          in: "query"
          required: false
          type: "string"
      responses:
        200:
          description: "search results matching criteria"
          schema:
            type: "array"
            items:
              type: "string"
      x-swagger-router-controller: "swagger_server.controllers.developers_controller"
